### PR TITLE
[ ❌ ABANDONED] Upgrade S6 Overlay to v3.0.0.0

### LINKED ISSUE #1: s6-overlay v3 is coming
I think it would be nice if this image has the latest version of s6-overlay installed.
https://github.com/just-containers/s6-overlay/releases/tag/v3.0.0.0

### PR DESCRIPTION
**Pull request by jaydrogers**
# Problem
* A new version of S6 Overlay is out

# TODO
- [x] Upgrade S6 overlay to version `3.0.0.2`

### Testing
- [ ] Ensure everything is working with the beta versions of the [PHP Docker Images](https://github.com/serversideup/docker-php/)
- [ ] Ensure commands can be passed to the images (like running `php artistan migrate`, etc)

# Assets
Testing image for this PR is located at:
```
serversideup/docker-baseimage-s6-overlay-ubuntu:edge-3-20.04
```
[View on Dockerhub  →](https://hub.docker.com/r/serversideup/docker-baseimage-s6-overlay-ubuntu/tags?page=1&name=edge-3-20.04)

### CODE REVIEW

**Comment by jaydrogers** [comment]
# Update:
- I have a Dockerfile in testing, but I am running into some issues

# Issues
- [ ] Running `docker run --rm -it localhost/docker-baseimage-s6-overlay-ubuntu bash` does not allow me to get into `bash`, it just sits there

# Gut feeling for resolution
- I need to dive into the S6 Overlay docs more and see what else changed (https://github.com/just-containers/s6-overlay)

# Assets
So far, I have changed the following files:

#### Dockerfile
https://github.com/serversideup/docker-baseimage-s6-overlay-ubuntu/blob/113c8accb3f57be705321616733fb2119a44f36b/Dockerfile#L4-L18

### CC
I am going to include @shinsenter on this message for latest update.

**Comment by shinsenter** [comment]
@jaydrogers 

bash just works for me.

```bash
docker run --platform linux/amd64 --rm -it serversideup/docker-baseimage-s6-overlay-ubuntu:edge-3-20.04 bash
```
Screen Shot 2022-01-26 at 12 55 23

**Comment by jaydrogers** [comment]
Thanks for letting me know! For some reason I'm still running into issues. Not sure if it is related to my M1 Max Macbook Pro...
docker

# Environment
```
Operating System Version:
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52

Docker Info:
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 34
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 3.841GiB
 Name: docker-desktop
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by shinsenter** [comment]
@jaydrogers 
Can you try again without the `-it` flags.

**Comment by jaydrogers** [comment]
I do get some sort of output that it's running, so it's weird that there is some sort of issue making it interactive and assigning a TTY. I have a feeling it has something to do with my M1 Mac and S6 Overlay's arch.

I will play around with this on an Intel Mac and will report back if I have issues.

image

**Comment by jaydrogers** [comment]
Thanks for your contribution @shinsenter! 

I am still having issues with S6 Overlay on my M1 Max and opened an issue here: https://github.com/just-containers/s6-overlay/issues/396

**Comment by shinsenter** [comment]
@jaydrogers 
I'm glad I was able to contribute to your efforts in this project.

**Comment by shinsenter** [comment]
@jaydrogers 

Changing `S6_OVERLAY_ARCH` to `aarch64` works for me.

**Comment by jaydrogers** [comment]
Just adding a note, the scope of this PR may be expanded because we'll need to Multi-arch support (which has been on my radar to learn ever since I got this Mac 😃)

Solution here: https://github.com/just-containers/s6-overlay/issues/396#issuecomment-1030437725

**Comment by shinsenter** [comment]
@jaydrogers I want S6v3-ready docker-php images, too. 😆

**Comment by jaydrogers** [comment]
Definitely! I will look into this more and will keep you posted.

Unfortunately I have another busy week and will take a look into all of this later this week. Thanks again for all your help!

**Comment by shinsenter** [comment]
@jaydrogers 
I see you seem busy and can't update the docker images yet, so I made my own version. 😬
https://hub.docker.com/u/shinsenter

**Comment by jaydrogers** [comment]
@shinsenter Yes, there's a lot of things going on in my personal life right now, but I still am anticipating getting to this within the next week or so.

It's too bad we won't be able to work together anymore, but I greatly appreciate your hard work. The power of open source 💪

**Pull request closed without merging**
